### ISSUE TITLE
Zdog[shapeName] is not a constructor 

### ISSUE THREAD

**Issue by gary149** [AlexandreBonaventure/vue-zdog#1]
Thanks Alexandre for this, declarative ZDog is awesome :)
Some shapes dont work, for example for ZPath or ZBox this error pops: 

```
[Vue warn]: Error in created hook (Promise/async): "TypeError: Zdog[shapeName] is not a constructor"
```

You can reproduce here: https://codesandbox.io/s/vue-template-vjc7w
Some other shapes like ZCone seems to render the wrong shape.
Also the peer dependency vue-runtimes-helpers seems required.

**Comment by AlexandreBonaventure** [comment]
> Also the peer dependency vue-runtimes-helpers seems required.
This is now fixed in 0.1.0.

Thanks!

As for Zdog[shapeName] error it is fixed via #3 in 0.1.1. You'll have to use `ZShape` instead of `ZPath`
