### ISSUE TITLE
Add ZGroup

### ISSUE THREAD

**Issue by vuchl** [AlexandreBonaventure/vue-zdog#2]
An API for https://zzz.dog/api#group would be nice too!

**Comment by vuchl** [comment]
@AlexandreBonaventure are you still maintaining actually?
Just saw you made a commit to the repo 👍

**Comment by AlexandreBonaventure** [comment]
of course I'm maintaining, just hadn't had the time yet. 
Thanks for the request, I intend to support that.

**Comment by AlexandreBonaventure** [comment]
available in v.0.2.0
